[package]
name = "tnsupdate"
version = "0.1.0"
authors = ["Andreas Rottmann <a.rottmann@gmx.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trust-dns = "0.17.0"
structopt = "0.3.1"
futures = "0.1.29"
failure = "0.1.5"
tokio = "0.1.22"
tokio-udp = "0.1.5"
